#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : eog
Version  : 42.3
Release  : 61
URL      : https://download.gnome.org/sources/eog/42/eog-42.3.tar.xz
Source0  : https://download.gnome.org/sources/eog/42/eog-42.3.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC-BY-SA-3.0 GPL-2.0
Requires: eog-bin = %{version}-%{release}
Requires: eog-data = %{version}-%{release}
Requires: eog-filemap = %{version}-%{release}
Requires: eog-lib = %{version}-%{release}
Requires: eog-license = %{version}-%{release}
Requires: eog-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gobject-introspection-dev
BuildRequires : itstool
BuildRequires : libexif-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libxml2-dev
BuildRequires : pkgconfig(exempi-2.0)
BuildRequires : pkgconfig(gnome-desktop-3.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(libhandy-1)
BuildRequires : pkgconfig(libpeas-1.0)
BuildRequires : pkgconfig(libportal)
BuildRequires : pkgconfig(librsvg-2.0)
BuildRequires : pkgconfig(shared-mime-info)

%description
Eye of GNOME: an image viewing and cataloging program
-----------------------------------------------------

%package bin
Summary: bin components for the eog package.
Group: Binaries
Requires: eog-data = %{version}-%{release}
Requires: eog-license = %{version}-%{release}
Requires: eog-filemap = %{version}-%{release}

%description bin
bin components for the eog package.


%package data
Summary: data components for the eog package.
Group: Data

%description data
data components for the eog package.


%package dev
Summary: dev components for the eog package.
Group: Development
Requires: eog-lib = %{version}-%{release}
Requires: eog-bin = %{version}-%{release}
Requires: eog-data = %{version}-%{release}
Provides: eog-devel = %{version}-%{release}
Requires: eog = %{version}-%{release}

%description dev
dev components for the eog package.


%package doc
Summary: doc components for the eog package.
Group: Documentation

%description doc
doc components for the eog package.


%package filemap
Summary: filemap components for the eog package.
Group: Default

%description filemap
filemap components for the eog package.


%package lib
Summary: lib components for the eog package.
Group: Libraries
Requires: eog-data = %{version}-%{release}
Requires: eog-license = %{version}-%{release}
Requires: eog-filemap = %{version}-%{release}

%description lib
lib components for the eog package.


%package license
Summary: license components for the eog package.
Group: Default

%description license
license components for the eog package.


%package locales
Summary: locales components for the eog package.
Group: Default

%description locales
locales components for the eog package.


%prep
%setup -q -n eog-42.3
cd %{_builddir}/eog-42.3
pushd ..
cp -a eog-42.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1659969069
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
mkdir -p %{buildroot}/usr/share/package-licenses/eog
cp %{_builddir}/eog-%{version}/COPYING %{buildroot}/usr/share/package-licenses/eog/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/eog-%{version}/help/C/license.page %{buildroot}/usr/share/package-licenses/eog/99449fd3e6417f1f32dbe2a5b252880badb25704
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang eog
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/eog/girepository-1.0/Eog-3.0.typelib
/usr/lib64/eog/plugins/fullscreen.plugin
/usr/lib64/eog/plugins/reload.plugin
/usr/lib64/eog/plugins/statusbar-date.plugin

%files bin
%defattr(-,root,root,-)
/usr/bin/eog
/usr/share/clear/optimized-elf/bin*

%files data
%defattr(-,root,root,-)
/usr/share/GConf/gsettings/eog.convert
/usr/share/applications/org.gnome.eog.desktop
/usr/share/eog/gir-1.0/Eog-3.0.gir
/usr/share/eog/icons/hicolor/16x16/actions/eog-plugin.png
/usr/share/eog/icons/hicolor/16x16/actions/slideshow-play.png
/usr/share/eog/icons/hicolor/22x22/actions/eog-plugin.png
/usr/share/eog/icons/hicolor/22x22/actions/slideshow-play.png
/usr/share/eog/icons/hicolor/24x24/actions/slideshow-play.png
/usr/share/eog/icons/hicolor/32x32/actions/eog-plugin.png
/usr/share/eog/icons/hicolor/32x32/actions/slideshow-play.png
/usr/share/eog/icons/hicolor/48x48/actions/slideshow-play.png
/usr/share/eog/icons/hicolor/scalable/actions/eog-image-gallery-symbolic.svg
/usr/share/eog/icons/hicolor/scalable/actions/eog-plugin.svg
/usr/share/eog/icons/hicolor/scalable/actions/slideshow-play.svg
/usr/share/glib-2.0/schemas/org.gnome.eog.enums.xml
/usr/share/glib-2.0/schemas/org.gnome.eog.gschema.xml
/usr/share/icons/hicolor/scalable/apps/org.gnome.eog.Devel.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.eog.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.eog-symbolic.svg
/usr/share/metainfo/eog.appdata.xml

%files dev
%defattr(-,root,root,-)
/usr/include/eog-3.0/eog/eog-application-activatable.h
/usr/include/eog-3.0/eog/eog-application.h
/usr/include/eog-3.0/eog/eog-clipboard-handler.h
/usr/include/eog-3.0/eog/eog-debug.h
/usr/include/eog-3.0/eog/eog-details-dialog.h
/usr/include/eog-3.0/eog/eog-enums.h
/usr/include/eog-3.0/eog/eog-exif-util.h
/usr/include/eog-3.0/eog/eog-file-chooser.h
/usr/include/eog-3.0/eog/eog-image-save-info.h
/usr/include/eog-3.0/eog/eog-image.h
/usr/include/eog-3.0/eog/eog-job-scheduler.h
/usr/include/eog-3.0/eog/eog-jobs.h
/usr/include/eog-3.0/eog/eog-list-store.h
/usr/include/eog-3.0/eog/eog-remote-presenter.h
/usr/include/eog-3.0/eog/eog-scroll-view.h
/usr/include/eog-3.0/eog/eog-sidebar.h
/usr/include/eog-3.0/eog/eog-statusbar.h
/usr/include/eog-3.0/eog/eog-thumb-nav.h
/usr/include/eog-3.0/eog/eog-thumb-view.h
/usr/include/eog-3.0/eog/eog-thumbnail.h
/usr/include/eog-3.0/eog/eog-transform.h
/usr/include/eog-3.0/eog/eog-uri-converter.h
/usr/include/eog-3.0/eog/eog-window-activatable.h
/usr/include/eog-3.0/eog/eog-window.h
/usr/lib64/pkgconfig/eog.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/eog/bug-filing.page
/usr/share/help/C/eog/commandline.page
/usr/share/help/C/eog/copy-paste.page
/usr/share/help/C/eog/default.page
/usr/share/help/C/eog/desktop-background.page
/usr/share/help/C/eog/develop.page
/usr/share/help/C/eog/documentation.page
/usr/share/help/C/eog/edit.page
/usr/share/help/C/eog/figures/multiple-convert.png
/usr/share/help/C/eog/figures/multiple-rename-count.png
/usr/share/help/C/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/C/eog/figures/org.gnome.eog.svg
/usr/share/help/C/eog/figures/plugins-all.png
/usr/share/help/C/eog/figures/prefs-plugins.png
/usr/share/help/C/eog/flip-rotate.page
/usr/share/help/C/eog/format-change.page
/usr/share/help/C/eog/formats-save.page
/usr/share/help/C/eog/formats-view.page
/usr/share/help/C/eog/index.page
/usr/share/help/C/eog/introduction.page
/usr/share/help/C/eog/legal.xml
/usr/share/help/C/eog/license.page
/usr/share/help/C/eog/open.page
/usr/share/help/C/eog/plugin-exif-digital.page
/usr/share/help/C/eog/plugin-fullscreen-background.page
/usr/share/help/C/eog/plugin-fullscreen-double-click.page
/usr/share/help/C/eog/plugin-python-console.page
/usr/share/help/C/eog/plugin-send-by-mail.page
/usr/share/help/C/eog/plugin-slideshow-shuffle.page
/usr/share/help/C/eog/plugin-zoom-width.page
/usr/share/help/C/eog/plugins.page
/usr/share/help/C/eog/preferences.page
/usr/share/help/C/eog/print.page
/usr/share/help/C/eog/rename-multiple.page
/usr/share/help/C/eog/slideshow.page
/usr/share/help/C/eog/translate.page
/usr/share/help/C/eog/view.page
/usr/share/help/C/eog/zoom.page
/usr/share/help/ar/eog/bug-filing.page
/usr/share/help/ar/eog/commandline.page
/usr/share/help/ar/eog/copy-paste.page
/usr/share/help/ar/eog/default.page
/usr/share/help/ar/eog/desktop-background.page
/usr/share/help/ar/eog/develop.page
/usr/share/help/ar/eog/documentation.page
/usr/share/help/ar/eog/edit.page
/usr/share/help/ar/eog/figures/multiple-convert.png
/usr/share/help/ar/eog/figures/multiple-rename-count.png
/usr/share/help/ar/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/ar/eog/figures/org.gnome.eog.svg
/usr/share/help/ar/eog/figures/plugins-all.png
/usr/share/help/ar/eog/figures/prefs-plugins.png
/usr/share/help/ar/eog/flip-rotate.page
/usr/share/help/ar/eog/format-change.page
/usr/share/help/ar/eog/formats-save.page
/usr/share/help/ar/eog/formats-view.page
/usr/share/help/ar/eog/index.page
/usr/share/help/ar/eog/introduction.page
/usr/share/help/ar/eog/legal.xml
/usr/share/help/ar/eog/license.page
/usr/share/help/ar/eog/open.page
/usr/share/help/ar/eog/plugin-exif-digital.page
/usr/share/help/ar/eog/plugin-fullscreen-background.page
/usr/share/help/ar/eog/plugin-fullscreen-double-click.page
/usr/share/help/ar/eog/plugin-python-console.page
/usr/share/help/ar/eog/plugin-send-by-mail.page
/usr/share/help/ar/eog/plugin-slideshow-shuffle.page
/usr/share/help/ar/eog/plugin-zoom-width.page
/usr/share/help/ar/eog/plugins.page
/usr/share/help/ar/eog/preferences.page
/usr/share/help/ar/eog/print.page
/usr/share/help/ar/eog/rename-multiple.page
/usr/share/help/ar/eog/slideshow.page
/usr/share/help/ar/eog/translate.page
/usr/share/help/ar/eog/view.page
/usr/share/help/ar/eog/zoom.page
/usr/share/help/ca/eog/bug-filing.page
/usr/share/help/ca/eog/commandline.page
/usr/share/help/ca/eog/copy-paste.page
/usr/share/help/ca/eog/default.page
/usr/share/help/ca/eog/desktop-background.page
/usr/share/help/ca/eog/develop.page
/usr/share/help/ca/eog/documentation.page
/usr/share/help/ca/eog/edit.page
/usr/share/help/ca/eog/figures/multiple-convert.png
/usr/share/help/ca/eog/figures/multiple-rename-count.png
/usr/share/help/ca/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/ca/eog/figures/org.gnome.eog.svg
/usr/share/help/ca/eog/figures/plugins-all.png
/usr/share/help/ca/eog/figures/prefs-plugins.png
/usr/share/help/ca/eog/flip-rotate.page
/usr/share/help/ca/eog/format-change.page
/usr/share/help/ca/eog/formats-save.page
/usr/share/help/ca/eog/formats-view.page
/usr/share/help/ca/eog/index.page
/usr/share/help/ca/eog/introduction.page
/usr/share/help/ca/eog/legal.xml
/usr/share/help/ca/eog/license.page
/usr/share/help/ca/eog/open.page
/usr/share/help/ca/eog/plugin-exif-digital.page
/usr/share/help/ca/eog/plugin-fullscreen-background.page
/usr/share/help/ca/eog/plugin-fullscreen-double-click.page
/usr/share/help/ca/eog/plugin-python-console.page
/usr/share/help/ca/eog/plugin-send-by-mail.page
/usr/share/help/ca/eog/plugin-slideshow-shuffle.page
/usr/share/help/ca/eog/plugin-zoom-width.page
/usr/share/help/ca/eog/plugins.page
/usr/share/help/ca/eog/preferences.page
/usr/share/help/ca/eog/print.page
/usr/share/help/ca/eog/rename-multiple.page
/usr/share/help/ca/eog/slideshow.page
/usr/share/help/ca/eog/translate.page
/usr/share/help/ca/eog/view.page
/usr/share/help/ca/eog/zoom.page
/usr/share/help/cs/eog/bug-filing.page
/usr/share/help/cs/eog/commandline.page
/usr/share/help/cs/eog/copy-paste.page
/usr/share/help/cs/eog/default.page
/usr/share/help/cs/eog/desktop-background.page
/usr/share/help/cs/eog/develop.page
/usr/share/help/cs/eog/documentation.page
/usr/share/help/cs/eog/edit.page
/usr/share/help/cs/eog/figures/multiple-convert.png
/usr/share/help/cs/eog/figures/multiple-rename-count.png
/usr/share/help/cs/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/cs/eog/figures/org.gnome.eog.svg
/usr/share/help/cs/eog/figures/plugins-all.png
/usr/share/help/cs/eog/figures/prefs-plugins.png
/usr/share/help/cs/eog/flip-rotate.page
/usr/share/help/cs/eog/format-change.page
/usr/share/help/cs/eog/formats-save.page
/usr/share/help/cs/eog/formats-view.page
/usr/share/help/cs/eog/index.page
/usr/share/help/cs/eog/introduction.page
/usr/share/help/cs/eog/legal.xml
/usr/share/help/cs/eog/license.page
/usr/share/help/cs/eog/open.page
/usr/share/help/cs/eog/plugin-exif-digital.page
/usr/share/help/cs/eog/plugin-fullscreen-background.page
/usr/share/help/cs/eog/plugin-fullscreen-double-click.page
/usr/share/help/cs/eog/plugin-python-console.page
/usr/share/help/cs/eog/plugin-send-by-mail.page
/usr/share/help/cs/eog/plugin-slideshow-shuffle.page
/usr/share/help/cs/eog/plugin-zoom-width.page
/usr/share/help/cs/eog/plugins.page
/usr/share/help/cs/eog/preferences.page
/usr/share/help/cs/eog/print.page
/usr/share/help/cs/eog/rename-multiple.page
/usr/share/help/cs/eog/slideshow.page
/usr/share/help/cs/eog/translate.page
/usr/share/help/cs/eog/view.page
/usr/share/help/cs/eog/zoom.page
/usr/share/help/da/eog/bug-filing.page
/usr/share/help/da/eog/commandline.page
/usr/share/help/da/eog/copy-paste.page
/usr/share/help/da/eog/default.page
/usr/share/help/da/eog/desktop-background.page
/usr/share/help/da/eog/develop.page
/usr/share/help/da/eog/documentation.page
/usr/share/help/da/eog/edit.page
/usr/share/help/da/eog/figures/multiple-convert.png
/usr/share/help/da/eog/figures/multiple-rename-count.png
/usr/share/help/da/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/da/eog/figures/org.gnome.eog.svg
/usr/share/help/da/eog/figures/plugins-all.png
/usr/share/help/da/eog/figures/prefs-plugins.png
/usr/share/help/da/eog/flip-rotate.page
/usr/share/help/da/eog/format-change.page
/usr/share/help/da/eog/formats-save.page
/usr/share/help/da/eog/formats-view.page
/usr/share/help/da/eog/index.page
/usr/share/help/da/eog/introduction.page
/usr/share/help/da/eog/legal.xml
/usr/share/help/da/eog/license.page
/usr/share/help/da/eog/open.page
/usr/share/help/da/eog/plugin-exif-digital.page
/usr/share/help/da/eog/plugin-fullscreen-background.page
/usr/share/help/da/eog/plugin-fullscreen-double-click.page
/usr/share/help/da/eog/plugin-python-console.page
/usr/share/help/da/eog/plugin-send-by-mail.page
/usr/share/help/da/eog/plugin-slideshow-shuffle.page
/usr/share/help/da/eog/plugin-zoom-width.page
/usr/share/help/da/eog/plugins.page
/usr/share/help/da/eog/preferences.page
/usr/share/help/da/eog/print.page
/usr/share/help/da/eog/rename-multiple.page
/usr/share/help/da/eog/slideshow.page
/usr/share/help/da/eog/translate.page
/usr/share/help/da/eog/view.page
/usr/share/help/da/eog/zoom.page
/usr/share/help/de/eog/bug-filing.page
/usr/share/help/de/eog/commandline.page
/usr/share/help/de/eog/copy-paste.page
/usr/share/help/de/eog/default.page
/usr/share/help/de/eog/desktop-background.page
/usr/share/help/de/eog/develop.page
/usr/share/help/de/eog/documentation.page
/usr/share/help/de/eog/edit.page
/usr/share/help/de/eog/figures/multiple-convert.png
/usr/share/help/de/eog/figures/multiple-rename-count.png
/usr/share/help/de/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/de/eog/figures/org.gnome.eog.svg
/usr/share/help/de/eog/figures/plugins-all.png
/usr/share/help/de/eog/figures/prefs-plugins.png
/usr/share/help/de/eog/flip-rotate.page
/usr/share/help/de/eog/format-change.page
/usr/share/help/de/eog/formats-save.page
/usr/share/help/de/eog/formats-view.page
/usr/share/help/de/eog/index.page
/usr/share/help/de/eog/introduction.page
/usr/share/help/de/eog/legal.xml
/usr/share/help/de/eog/license.page
/usr/share/help/de/eog/open.page
/usr/share/help/de/eog/plugin-exif-digital.page
/usr/share/help/de/eog/plugin-fullscreen-background.page
/usr/share/help/de/eog/plugin-fullscreen-double-click.page
/usr/share/help/de/eog/plugin-python-console.page
/usr/share/help/de/eog/plugin-send-by-mail.page
/usr/share/help/de/eog/plugin-slideshow-shuffle.page
/usr/share/help/de/eog/plugin-zoom-width.page
/usr/share/help/de/eog/plugins.page
/usr/share/help/de/eog/preferences.page
/usr/share/help/de/eog/print.page
/usr/share/help/de/eog/rename-multiple.page
/usr/share/help/de/eog/slideshow.page
/usr/share/help/de/eog/translate.page
/usr/share/help/de/eog/view.page
/usr/share/help/de/eog/zoom.page
/usr/share/help/el/eog/bug-filing.page
/usr/share/help/el/eog/commandline.page
/usr/share/help/el/eog/copy-paste.page
/usr/share/help/el/eog/default.page
/usr/share/help/el/eog/desktop-background.page
/usr/share/help/el/eog/develop.page
/usr/share/help/el/eog/documentation.page
/usr/share/help/el/eog/edit.page
/usr/share/help/el/eog/figures/multiple-convert.png
/usr/share/help/el/eog/figures/multiple-rename-count.png
/usr/share/help/el/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/el/eog/figures/org.gnome.eog.svg
/usr/share/help/el/eog/figures/plugins-all.png
/usr/share/help/el/eog/figures/prefs-plugins.png
/usr/share/help/el/eog/flip-rotate.page
/usr/share/help/el/eog/format-change.page
/usr/share/help/el/eog/formats-save.page
/usr/share/help/el/eog/formats-view.page
/usr/share/help/el/eog/index.page
/usr/share/help/el/eog/introduction.page
/usr/share/help/el/eog/legal.xml
/usr/share/help/el/eog/license.page
/usr/share/help/el/eog/open.page
/usr/share/help/el/eog/plugin-exif-digital.page
/usr/share/help/el/eog/plugin-fullscreen-background.page
/usr/share/help/el/eog/plugin-fullscreen-double-click.page
/usr/share/help/el/eog/plugin-python-console.page
/usr/share/help/el/eog/plugin-send-by-mail.page
/usr/share/help/el/eog/plugin-slideshow-shuffle.page
/usr/share/help/el/eog/plugin-zoom-width.page
/usr/share/help/el/eog/plugins.page
/usr/share/help/el/eog/preferences.page
/usr/share/help/el/eog/print.page
/usr/share/help/el/eog/rename-multiple.page
/usr/share/help/el/eog/slideshow.page
/usr/share/help/el/eog/translate.page
/usr/share/help/el/eog/view.page
/usr/share/help/el/eog/zoom.page
/usr/share/help/en_GB/eog/bug-filing.page
/usr/share/help/en_GB/eog/commandline.page
/usr/share/help/en_GB/eog/copy-paste.page
/usr/share/help/en_GB/eog/default.page
/usr/share/help/en_GB/eog/desktop-background.page
/usr/share/help/en_GB/eog/develop.page
/usr/share/help/en_GB/eog/documentation.page
/usr/share/help/en_GB/eog/edit.page
/usr/share/help/en_GB/eog/figures/multiple-convert.png
/usr/share/help/en_GB/eog/figures/multiple-rename-count.png
/usr/share/help/en_GB/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/en_GB/eog/figures/org.gnome.eog.svg
/usr/share/help/en_GB/eog/figures/plugins-all.png
/usr/share/help/en_GB/eog/figures/prefs-plugins.png
/usr/share/help/en_GB/eog/flip-rotate.page
/usr/share/help/en_GB/eog/format-change.page
/usr/share/help/en_GB/eog/formats-save.page
/usr/share/help/en_GB/eog/formats-view.page
/usr/share/help/en_GB/eog/index.page
/usr/share/help/en_GB/eog/introduction.page
/usr/share/help/en_GB/eog/legal.xml
/usr/share/help/en_GB/eog/license.page
/usr/share/help/en_GB/eog/open.page
/usr/share/help/en_GB/eog/plugin-exif-digital.page
/usr/share/help/en_GB/eog/plugin-fullscreen-background.page
/usr/share/help/en_GB/eog/plugin-fullscreen-double-click.page
/usr/share/help/en_GB/eog/plugin-python-console.page
/usr/share/help/en_GB/eog/plugin-send-by-mail.page
/usr/share/help/en_GB/eog/plugin-slideshow-shuffle.page
/usr/share/help/en_GB/eog/plugin-zoom-width.page
/usr/share/help/en_GB/eog/plugins.page
/usr/share/help/en_GB/eog/preferences.page
/usr/share/help/en_GB/eog/print.page
/usr/share/help/en_GB/eog/rename-multiple.page
/usr/share/help/en_GB/eog/slideshow.page
/usr/share/help/en_GB/eog/translate.page
/usr/share/help/en_GB/eog/view.page
/usr/share/help/en_GB/eog/zoom.page
/usr/share/help/es/eog/bug-filing.page
/usr/share/help/es/eog/commandline.page
/usr/share/help/es/eog/copy-paste.page
/usr/share/help/es/eog/default.page
/usr/share/help/es/eog/desktop-background.page
/usr/share/help/es/eog/develop.page
/usr/share/help/es/eog/documentation.page
/usr/share/help/es/eog/edit.page
/usr/share/help/es/eog/figures/multiple-convert.png
/usr/share/help/es/eog/figures/multiple-rename-count.png
/usr/share/help/es/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/es/eog/figures/org.gnome.eog.svg
/usr/share/help/es/eog/figures/plugins-all.png
/usr/share/help/es/eog/figures/prefs-plugins.png
/usr/share/help/es/eog/flip-rotate.page
/usr/share/help/es/eog/format-change.page
/usr/share/help/es/eog/formats-save.page
/usr/share/help/es/eog/formats-view.page
/usr/share/help/es/eog/index.page
/usr/share/help/es/eog/introduction.page
/usr/share/help/es/eog/legal.xml
/usr/share/help/es/eog/license.page
/usr/share/help/es/eog/open.page
/usr/share/help/es/eog/plugin-exif-digital.page
/usr/share/help/es/eog/plugin-fullscreen-background.page
/usr/share/help/es/eog/plugin-fullscreen-double-click.page
/usr/share/help/es/eog/plugin-python-console.page
/usr/share/help/es/eog/plugin-send-by-mail.page
/usr/share/help/es/eog/plugin-slideshow-shuffle.page
/usr/share/help/es/eog/plugin-zoom-width.page
/usr/share/help/es/eog/plugins.page
/usr/share/help/es/eog/preferences.page
/usr/share/help/es/eog/print.page
/usr/share/help/es/eog/rename-multiple.page
/usr/share/help/es/eog/slideshow.page
/usr/share/help/es/eog/translate.page
/usr/share/help/es/eog/view.page
/usr/share/help/es/eog/zoom.page
/usr/share/help/eu/eog/bug-filing.page
/usr/share/help/eu/eog/commandline.page
/usr/share/help/eu/eog/copy-paste.page
/usr/share/help/eu/eog/default.page
/usr/share/help/eu/eog/desktop-background.page
/usr/share/help/eu/eog/develop.page
/usr/share/help/eu/eog/documentation.page
/usr/share/help/eu/eog/edit.page
/usr/share/help/eu/eog/figures/multiple-convert.png
/usr/share/help/eu/eog/figures/multiple-rename-count.png
/usr/share/help/eu/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/eu/eog/figures/org.gnome.eog.svg
/usr/share/help/eu/eog/figures/plugins-all.png
/usr/share/help/eu/eog/figures/prefs-plugins.png
/usr/share/help/eu/eog/flip-rotate.page
/usr/share/help/eu/eog/format-change.page
/usr/share/help/eu/eog/formats-save.page
/usr/share/help/eu/eog/formats-view.page
/usr/share/help/eu/eog/index.page
/usr/share/help/eu/eog/introduction.page
/usr/share/help/eu/eog/legal.xml
/usr/share/help/eu/eog/license.page
/usr/share/help/eu/eog/open.page
/usr/share/help/eu/eog/plugin-exif-digital.page
/usr/share/help/eu/eog/plugin-fullscreen-background.page
/usr/share/help/eu/eog/plugin-fullscreen-double-click.page
/usr/share/help/eu/eog/plugin-python-console.page
/usr/share/help/eu/eog/plugin-send-by-mail.page
/usr/share/help/eu/eog/plugin-slideshow-shuffle.page
/usr/share/help/eu/eog/plugin-zoom-width.page
/usr/share/help/eu/eog/plugins.page
/usr/share/help/eu/eog/preferences.page
/usr/share/help/eu/eog/print.page
/usr/share/help/eu/eog/rename-multiple.page
/usr/share/help/eu/eog/slideshow.page
/usr/share/help/eu/eog/translate.page
/usr/share/help/eu/eog/view.page
/usr/share/help/eu/eog/zoom.page
/usr/share/help/fi/eog/bug-filing.page
/usr/share/help/fi/eog/commandline.page
/usr/share/help/fi/eog/copy-paste.page
/usr/share/help/fi/eog/default.page
/usr/share/help/fi/eog/desktop-background.page
/usr/share/help/fi/eog/develop.page
/usr/share/help/fi/eog/documentation.page
/usr/share/help/fi/eog/edit.page
/usr/share/help/fi/eog/figures/multiple-convert.png
/usr/share/help/fi/eog/figures/multiple-rename-count.png
/usr/share/help/fi/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/fi/eog/figures/org.gnome.eog.svg
/usr/share/help/fi/eog/figures/plugins-all.png
/usr/share/help/fi/eog/figures/prefs-plugins.png
/usr/share/help/fi/eog/flip-rotate.page
/usr/share/help/fi/eog/format-change.page
/usr/share/help/fi/eog/formats-save.page
/usr/share/help/fi/eog/formats-view.page
/usr/share/help/fi/eog/index.page
/usr/share/help/fi/eog/introduction.page
/usr/share/help/fi/eog/legal.xml
/usr/share/help/fi/eog/license.page
/usr/share/help/fi/eog/open.page
/usr/share/help/fi/eog/plugin-exif-digital.page
/usr/share/help/fi/eog/plugin-fullscreen-background.page
/usr/share/help/fi/eog/plugin-fullscreen-double-click.page
/usr/share/help/fi/eog/plugin-python-console.page
/usr/share/help/fi/eog/plugin-send-by-mail.page
/usr/share/help/fi/eog/plugin-slideshow-shuffle.page
/usr/share/help/fi/eog/plugin-zoom-width.page
/usr/share/help/fi/eog/plugins.page
/usr/share/help/fi/eog/preferences.page
/usr/share/help/fi/eog/print.page
/usr/share/help/fi/eog/rename-multiple.page
/usr/share/help/fi/eog/slideshow.page
/usr/share/help/fi/eog/translate.page
/usr/share/help/fi/eog/view.page
/usr/share/help/fi/eog/zoom.page
/usr/share/help/fr/eog/bug-filing.page
/usr/share/help/fr/eog/commandline.page
/usr/share/help/fr/eog/copy-paste.page
/usr/share/help/fr/eog/default.page
/usr/share/help/fr/eog/desktop-background.page
/usr/share/help/fr/eog/develop.page
/usr/share/help/fr/eog/documentation.page
/usr/share/help/fr/eog/edit.page
/usr/share/help/fr/eog/figures/multiple-convert.png
/usr/share/help/fr/eog/figures/multiple-rename-count.png
/usr/share/help/fr/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/fr/eog/figures/org.gnome.eog.svg
/usr/share/help/fr/eog/figures/plugins-all.png
/usr/share/help/fr/eog/figures/prefs-plugins.png
/usr/share/help/fr/eog/flip-rotate.page
/usr/share/help/fr/eog/format-change.page
/usr/share/help/fr/eog/formats-save.page
/usr/share/help/fr/eog/formats-view.page
/usr/share/help/fr/eog/index.page
/usr/share/help/fr/eog/introduction.page
/usr/share/help/fr/eog/legal.xml
/usr/share/help/fr/eog/license.page
/usr/share/help/fr/eog/open.page
/usr/share/help/fr/eog/plugin-exif-digital.page
/usr/share/help/fr/eog/plugin-fullscreen-background.page
/usr/share/help/fr/eog/plugin-fullscreen-double-click.page
/usr/share/help/fr/eog/plugin-python-console.page
/usr/share/help/fr/eog/plugin-send-by-mail.page
/usr/share/help/fr/eog/plugin-slideshow-shuffle.page
/usr/share/help/fr/eog/plugin-zoom-width.page
/usr/share/help/fr/eog/plugins.page
/usr/share/help/fr/eog/preferences.page
/usr/share/help/fr/eog/print.page
/usr/share/help/fr/eog/rename-multiple.page
/usr/share/help/fr/eog/slideshow.page
/usr/share/help/fr/eog/translate.page
/usr/share/help/fr/eog/view.page
/usr/share/help/fr/eog/zoom.page
/usr/share/help/gl/eog/bug-filing.page
/usr/share/help/gl/eog/commandline.page
/usr/share/help/gl/eog/copy-paste.page
/usr/share/help/gl/eog/default.page
/usr/share/help/gl/eog/desktop-background.page
/usr/share/help/gl/eog/develop.page
/usr/share/help/gl/eog/documentation.page
/usr/share/help/gl/eog/edit.page
/usr/share/help/gl/eog/figures/multiple-convert.png
/usr/share/help/gl/eog/figures/multiple-rename-count.png
/usr/share/help/gl/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/gl/eog/figures/org.gnome.eog.svg
/usr/share/help/gl/eog/figures/plugins-all.png
/usr/share/help/gl/eog/figures/prefs-plugins.png
/usr/share/help/gl/eog/flip-rotate.page
/usr/share/help/gl/eog/format-change.page
/usr/share/help/gl/eog/formats-save.page
/usr/share/help/gl/eog/formats-view.page
/usr/share/help/gl/eog/index.page
/usr/share/help/gl/eog/introduction.page
/usr/share/help/gl/eog/legal.xml
/usr/share/help/gl/eog/license.page
/usr/share/help/gl/eog/open.page
/usr/share/help/gl/eog/plugin-exif-digital.page
/usr/share/help/gl/eog/plugin-fullscreen-background.page
/usr/share/help/gl/eog/plugin-fullscreen-double-click.page
/usr/share/help/gl/eog/plugin-python-console.page
/usr/share/help/gl/eog/plugin-send-by-mail.page
/usr/share/help/gl/eog/plugin-slideshow-shuffle.page
/usr/share/help/gl/eog/plugin-zoom-width.page
/usr/share/help/gl/eog/plugins.page
/usr/share/help/gl/eog/preferences.page
/usr/share/help/gl/eog/print.page
/usr/share/help/gl/eog/rename-multiple.page
/usr/share/help/gl/eog/slideshow.page
/usr/share/help/gl/eog/translate.page
/usr/share/help/gl/eog/view.page
/usr/share/help/gl/eog/zoom.page
/usr/share/help/hu/eog/bug-filing.page
/usr/share/help/hu/eog/commandline.page
/usr/share/help/hu/eog/copy-paste.page
/usr/share/help/hu/eog/default.page
/usr/share/help/hu/eog/desktop-background.page
/usr/share/help/hu/eog/develop.page
/usr/share/help/hu/eog/documentation.page
/usr/share/help/hu/eog/edit.page
/usr/share/help/hu/eog/figures/multiple-convert.png
/usr/share/help/hu/eog/figures/multiple-rename-count.png
/usr/share/help/hu/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/hu/eog/figures/org.gnome.eog.svg
/usr/share/help/hu/eog/figures/plugins-all.png
/usr/share/help/hu/eog/figures/prefs-plugins.png
/usr/share/help/hu/eog/flip-rotate.page
/usr/share/help/hu/eog/format-change.page
/usr/share/help/hu/eog/formats-save.page
/usr/share/help/hu/eog/formats-view.page
/usr/share/help/hu/eog/index.page
/usr/share/help/hu/eog/introduction.page
/usr/share/help/hu/eog/legal.xml
/usr/share/help/hu/eog/license.page
/usr/share/help/hu/eog/open.page
/usr/share/help/hu/eog/plugin-exif-digital.page
/usr/share/help/hu/eog/plugin-fullscreen-background.page
/usr/share/help/hu/eog/plugin-fullscreen-double-click.page
/usr/share/help/hu/eog/plugin-python-console.page
/usr/share/help/hu/eog/plugin-send-by-mail.page
/usr/share/help/hu/eog/plugin-slideshow-shuffle.page
/usr/share/help/hu/eog/plugin-zoom-width.page
/usr/share/help/hu/eog/plugins.page
/usr/share/help/hu/eog/preferences.page
/usr/share/help/hu/eog/print.page
/usr/share/help/hu/eog/rename-multiple.page
/usr/share/help/hu/eog/slideshow.page
/usr/share/help/hu/eog/translate.page
/usr/share/help/hu/eog/view.page
/usr/share/help/hu/eog/zoom.page
/usr/share/help/id/eog/bug-filing.page
/usr/share/help/id/eog/commandline.page
/usr/share/help/id/eog/copy-paste.page
/usr/share/help/id/eog/default.page
/usr/share/help/id/eog/desktop-background.page
/usr/share/help/id/eog/develop.page
/usr/share/help/id/eog/documentation.page
/usr/share/help/id/eog/edit.page
/usr/share/help/id/eog/figures/multiple-convert.png
/usr/share/help/id/eog/figures/multiple-rename-count.png
/usr/share/help/id/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/id/eog/figures/org.gnome.eog.svg
/usr/share/help/id/eog/figures/plugins-all.png
/usr/share/help/id/eog/figures/prefs-plugins.png
/usr/share/help/id/eog/flip-rotate.page
/usr/share/help/id/eog/format-change.page
/usr/share/help/id/eog/formats-save.page
/usr/share/help/id/eog/formats-view.page
/usr/share/help/id/eog/index.page
/usr/share/help/id/eog/introduction.page
/usr/share/help/id/eog/legal.xml
/usr/share/help/id/eog/license.page
/usr/share/help/id/eog/open.page
/usr/share/help/id/eog/plugin-exif-digital.page
/usr/share/help/id/eog/plugin-fullscreen-background.page
/usr/share/help/id/eog/plugin-fullscreen-double-click.page
/usr/share/help/id/eog/plugin-python-console.page
/usr/share/help/id/eog/plugin-send-by-mail.page
/usr/share/help/id/eog/plugin-slideshow-shuffle.page
/usr/share/help/id/eog/plugin-zoom-width.page
/usr/share/help/id/eog/plugins.page
/usr/share/help/id/eog/preferences.page
/usr/share/help/id/eog/print.page
/usr/share/help/id/eog/rename-multiple.page
/usr/share/help/id/eog/slideshow.page
/usr/share/help/id/eog/translate.page
/usr/share/help/id/eog/view.page
/usr/share/help/id/eog/zoom.page
/usr/share/help/it/eog/bug-filing.page
/usr/share/help/it/eog/commandline.page
/usr/share/help/it/eog/copy-paste.page
/usr/share/help/it/eog/default.page
/usr/share/help/it/eog/desktop-background.page
/usr/share/help/it/eog/develop.page
/usr/share/help/it/eog/documentation.page
/usr/share/help/it/eog/edit.page
/usr/share/help/it/eog/figures/multiple-convert.png
/usr/share/help/it/eog/figures/multiple-rename-count.png
/usr/share/help/it/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/it/eog/figures/org.gnome.eog.svg
/usr/share/help/it/eog/figures/plugins-all.png
/usr/share/help/it/eog/figures/prefs-plugins.png
/usr/share/help/it/eog/flip-rotate.page
/usr/share/help/it/eog/format-change.page
/usr/share/help/it/eog/formats-save.page
/usr/share/help/it/eog/formats-view.page
/usr/share/help/it/eog/index.page
/usr/share/help/it/eog/introduction.page
/usr/share/help/it/eog/legal.xml
/usr/share/help/it/eog/license.page
/usr/share/help/it/eog/open.page
/usr/share/help/it/eog/plugin-exif-digital.page
/usr/share/help/it/eog/plugin-fullscreen-background.page
/usr/share/help/it/eog/plugin-fullscreen-double-click.page
/usr/share/help/it/eog/plugin-python-console.page
/usr/share/help/it/eog/plugin-send-by-mail.page
/usr/share/help/it/eog/plugin-slideshow-shuffle.page
/usr/share/help/it/eog/plugin-zoom-width.page
/usr/share/help/it/eog/plugins.page
/usr/share/help/it/eog/preferences.page
/usr/share/help/it/eog/print.page
/usr/share/help/it/eog/rename-multiple.page
/usr/share/help/it/eog/slideshow.page
/usr/share/help/it/eog/translate.page
/usr/share/help/it/eog/view.page
/usr/share/help/it/eog/zoom.page
/usr/share/help/ja/eog/bug-filing.page
/usr/share/help/ja/eog/commandline.page
/usr/share/help/ja/eog/copy-paste.page
/usr/share/help/ja/eog/default.page
/usr/share/help/ja/eog/desktop-background.page
/usr/share/help/ja/eog/develop.page
/usr/share/help/ja/eog/documentation.page
/usr/share/help/ja/eog/edit.page
/usr/share/help/ja/eog/figures/multiple-convert.png
/usr/share/help/ja/eog/figures/multiple-rename-count.png
/usr/share/help/ja/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/ja/eog/figures/org.gnome.eog.svg
/usr/share/help/ja/eog/figures/plugins-all.png
/usr/share/help/ja/eog/figures/prefs-plugins.png
/usr/share/help/ja/eog/flip-rotate.page
/usr/share/help/ja/eog/format-change.page
/usr/share/help/ja/eog/formats-save.page
/usr/share/help/ja/eog/formats-view.page
/usr/share/help/ja/eog/index.page
/usr/share/help/ja/eog/introduction.page
/usr/share/help/ja/eog/legal.xml
/usr/share/help/ja/eog/license.page
/usr/share/help/ja/eog/open.page
/usr/share/help/ja/eog/plugin-exif-digital.page
/usr/share/help/ja/eog/plugin-fullscreen-background.page
/usr/share/help/ja/eog/plugin-fullscreen-double-click.page
/usr/share/help/ja/eog/plugin-python-console.page
/usr/share/help/ja/eog/plugin-send-by-mail.page
/usr/share/help/ja/eog/plugin-slideshow-shuffle.page
/usr/share/help/ja/eog/plugin-zoom-width.page
/usr/share/help/ja/eog/plugins.page
/usr/share/help/ja/eog/preferences.page
/usr/share/help/ja/eog/print.page
/usr/share/help/ja/eog/rename-multiple.page
/usr/share/help/ja/eog/slideshow.page
/usr/share/help/ja/eog/translate.page
/usr/share/help/ja/eog/view.page
/usr/share/help/ja/eog/zoom.page
/usr/share/help/ko/eog/bug-filing.page
/usr/share/help/ko/eog/commandline.page
/usr/share/help/ko/eog/copy-paste.page
/usr/share/help/ko/eog/default.page
/usr/share/help/ko/eog/desktop-background.page
/usr/share/help/ko/eog/develop.page
/usr/share/help/ko/eog/documentation.page
/usr/share/help/ko/eog/edit.page
/usr/share/help/ko/eog/figures/multiple-convert.png
/usr/share/help/ko/eog/figures/multiple-rename-count.png
/usr/share/help/ko/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/ko/eog/figures/org.gnome.eog.svg
/usr/share/help/ko/eog/figures/plugins-all.png
/usr/share/help/ko/eog/figures/prefs-plugins.png
/usr/share/help/ko/eog/flip-rotate.page
/usr/share/help/ko/eog/format-change.page
/usr/share/help/ko/eog/formats-save.page
/usr/share/help/ko/eog/formats-view.page
/usr/share/help/ko/eog/index.page
/usr/share/help/ko/eog/introduction.page
/usr/share/help/ko/eog/legal.xml
/usr/share/help/ko/eog/license.page
/usr/share/help/ko/eog/open.page
/usr/share/help/ko/eog/plugin-exif-digital.page
/usr/share/help/ko/eog/plugin-fullscreen-background.page
/usr/share/help/ko/eog/plugin-fullscreen-double-click.page
/usr/share/help/ko/eog/plugin-python-console.page
/usr/share/help/ko/eog/plugin-send-by-mail.page
/usr/share/help/ko/eog/plugin-slideshow-shuffle.page
/usr/share/help/ko/eog/plugin-zoom-width.page
/usr/share/help/ko/eog/plugins.page
/usr/share/help/ko/eog/preferences.page
/usr/share/help/ko/eog/print.page
/usr/share/help/ko/eog/rename-multiple.page
/usr/share/help/ko/eog/slideshow.page
/usr/share/help/ko/eog/translate.page
/usr/share/help/ko/eog/view.page
/usr/share/help/ko/eog/zoom.page
/usr/share/help/lv/eog/bug-filing.page
/usr/share/help/lv/eog/commandline.page
/usr/share/help/lv/eog/copy-paste.page
/usr/share/help/lv/eog/default.page
/usr/share/help/lv/eog/desktop-background.page
/usr/share/help/lv/eog/develop.page
/usr/share/help/lv/eog/documentation.page
/usr/share/help/lv/eog/edit.page
/usr/share/help/lv/eog/figures/multiple-convert.png
/usr/share/help/lv/eog/figures/multiple-rename-count.png
/usr/share/help/lv/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/lv/eog/figures/org.gnome.eog.svg
/usr/share/help/lv/eog/figures/plugins-all.png
/usr/share/help/lv/eog/figures/prefs-plugins.png
/usr/share/help/lv/eog/flip-rotate.page
/usr/share/help/lv/eog/format-change.page
/usr/share/help/lv/eog/formats-save.page
/usr/share/help/lv/eog/formats-view.page
/usr/share/help/lv/eog/index.page
/usr/share/help/lv/eog/introduction.page
/usr/share/help/lv/eog/legal.xml
/usr/share/help/lv/eog/license.page
/usr/share/help/lv/eog/open.page
/usr/share/help/lv/eog/plugin-exif-digital.page
/usr/share/help/lv/eog/plugin-fullscreen-background.page
/usr/share/help/lv/eog/plugin-fullscreen-double-click.page
/usr/share/help/lv/eog/plugin-python-console.page
/usr/share/help/lv/eog/plugin-send-by-mail.page
/usr/share/help/lv/eog/plugin-slideshow-shuffle.page
/usr/share/help/lv/eog/plugin-zoom-width.page
/usr/share/help/lv/eog/plugins.page
/usr/share/help/lv/eog/preferences.page
/usr/share/help/lv/eog/print.page
/usr/share/help/lv/eog/rename-multiple.page
/usr/share/help/lv/eog/slideshow.page
/usr/share/help/lv/eog/translate.page
/usr/share/help/lv/eog/view.page
/usr/share/help/lv/eog/zoom.page
/usr/share/help/ne/eog/bug-filing.page
/usr/share/help/ne/eog/commandline.page
/usr/share/help/ne/eog/copy-paste.page
/usr/share/help/ne/eog/default.page
/usr/share/help/ne/eog/desktop-background.page
/usr/share/help/ne/eog/develop.page
/usr/share/help/ne/eog/documentation.page
/usr/share/help/ne/eog/edit.page
/usr/share/help/ne/eog/figures/multiple-convert.png
/usr/share/help/ne/eog/figures/multiple-rename-count.png
/usr/share/help/ne/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/ne/eog/figures/org.gnome.eog.svg
/usr/share/help/ne/eog/figures/plugins-all.png
/usr/share/help/ne/eog/figures/prefs-plugins.png
/usr/share/help/ne/eog/flip-rotate.page
/usr/share/help/ne/eog/format-change.page
/usr/share/help/ne/eog/formats-save.page
/usr/share/help/ne/eog/formats-view.page
/usr/share/help/ne/eog/index.page
/usr/share/help/ne/eog/introduction.page
/usr/share/help/ne/eog/legal.xml
/usr/share/help/ne/eog/license.page
/usr/share/help/ne/eog/open.page
/usr/share/help/ne/eog/plugin-exif-digital.page
/usr/share/help/ne/eog/plugin-fullscreen-background.page
/usr/share/help/ne/eog/plugin-fullscreen-double-click.page
/usr/share/help/ne/eog/plugin-python-console.page
/usr/share/help/ne/eog/plugin-send-by-mail.page
/usr/share/help/ne/eog/plugin-slideshow-shuffle.page
/usr/share/help/ne/eog/plugin-zoom-width.page
/usr/share/help/ne/eog/plugins.page
/usr/share/help/ne/eog/preferences.page
/usr/share/help/ne/eog/print.page
/usr/share/help/ne/eog/rename-multiple.page
/usr/share/help/ne/eog/slideshow.page
/usr/share/help/ne/eog/translate.page
/usr/share/help/ne/eog/view.page
/usr/share/help/ne/eog/zoom.page
/usr/share/help/oc/eog/bug-filing.page
/usr/share/help/oc/eog/commandline.page
/usr/share/help/oc/eog/copy-paste.page
/usr/share/help/oc/eog/default.page
/usr/share/help/oc/eog/desktop-background.page
/usr/share/help/oc/eog/develop.page
/usr/share/help/oc/eog/documentation.page
/usr/share/help/oc/eog/edit.page
/usr/share/help/oc/eog/figures/multiple-convert.png
/usr/share/help/oc/eog/figures/multiple-rename-count.png
/usr/share/help/oc/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/oc/eog/figures/org.gnome.eog.svg
/usr/share/help/oc/eog/figures/plugins-all.png
/usr/share/help/oc/eog/figures/prefs-plugins.png
/usr/share/help/oc/eog/flip-rotate.page
/usr/share/help/oc/eog/format-change.page
/usr/share/help/oc/eog/formats-save.page
/usr/share/help/oc/eog/formats-view.page
/usr/share/help/oc/eog/index.page
/usr/share/help/oc/eog/introduction.page
/usr/share/help/oc/eog/legal.xml
/usr/share/help/oc/eog/license.page
/usr/share/help/oc/eog/open.page
/usr/share/help/oc/eog/plugin-exif-digital.page
/usr/share/help/oc/eog/plugin-fullscreen-background.page
/usr/share/help/oc/eog/plugin-fullscreen-double-click.page
/usr/share/help/oc/eog/plugin-python-console.page
/usr/share/help/oc/eog/plugin-send-by-mail.page
/usr/share/help/oc/eog/plugin-slideshow-shuffle.page
/usr/share/help/oc/eog/plugin-zoom-width.page
/usr/share/help/oc/eog/plugins.page
/usr/share/help/oc/eog/preferences.page
/usr/share/help/oc/eog/print.page
/usr/share/help/oc/eog/rename-multiple.page
/usr/share/help/oc/eog/slideshow.page
/usr/share/help/oc/eog/translate.page
/usr/share/help/oc/eog/view.page
/usr/share/help/oc/eog/zoom.page
/usr/share/help/pa/eog/bug-filing.page
/usr/share/help/pa/eog/commandline.page
/usr/share/help/pa/eog/copy-paste.page
/usr/share/help/pa/eog/default.page
/usr/share/help/pa/eog/desktop-background.page
/usr/share/help/pa/eog/develop.page
/usr/share/help/pa/eog/documentation.page
/usr/share/help/pa/eog/edit.page
/usr/share/help/pa/eog/figures/multiple-convert.png
/usr/share/help/pa/eog/figures/multiple-rename-count.png
/usr/share/help/pa/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/pa/eog/figures/org.gnome.eog.svg
/usr/share/help/pa/eog/figures/plugins-all.png
/usr/share/help/pa/eog/figures/prefs-plugins.png
/usr/share/help/pa/eog/flip-rotate.page
/usr/share/help/pa/eog/format-change.page
/usr/share/help/pa/eog/formats-save.page
/usr/share/help/pa/eog/formats-view.page
/usr/share/help/pa/eog/index.page
/usr/share/help/pa/eog/introduction.page
/usr/share/help/pa/eog/legal.xml
/usr/share/help/pa/eog/license.page
/usr/share/help/pa/eog/open.page
/usr/share/help/pa/eog/plugin-exif-digital.page
/usr/share/help/pa/eog/plugin-fullscreen-background.page
/usr/share/help/pa/eog/plugin-fullscreen-double-click.page
/usr/share/help/pa/eog/plugin-python-console.page
/usr/share/help/pa/eog/plugin-send-by-mail.page
/usr/share/help/pa/eog/plugin-slideshow-shuffle.page
/usr/share/help/pa/eog/plugin-zoom-width.page
/usr/share/help/pa/eog/plugins.page
/usr/share/help/pa/eog/preferences.page
/usr/share/help/pa/eog/print.page
/usr/share/help/pa/eog/rename-multiple.page
/usr/share/help/pa/eog/slideshow.page
/usr/share/help/pa/eog/translate.page
/usr/share/help/pa/eog/view.page
/usr/share/help/pa/eog/zoom.page
/usr/share/help/pl/eog/bug-filing.page
/usr/share/help/pl/eog/commandline.page
/usr/share/help/pl/eog/copy-paste.page
/usr/share/help/pl/eog/default.page
/usr/share/help/pl/eog/desktop-background.page
/usr/share/help/pl/eog/develop.page
/usr/share/help/pl/eog/documentation.page
/usr/share/help/pl/eog/edit.page
/usr/share/help/pl/eog/figures/multiple-convert.png
/usr/share/help/pl/eog/figures/multiple-rename-count.png
/usr/share/help/pl/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/pl/eog/figures/org.gnome.eog.svg
/usr/share/help/pl/eog/figures/plugins-all.png
/usr/share/help/pl/eog/figures/prefs-plugins.png
/usr/share/help/pl/eog/flip-rotate.page
/usr/share/help/pl/eog/format-change.page
/usr/share/help/pl/eog/formats-save.page
/usr/share/help/pl/eog/formats-view.page
/usr/share/help/pl/eog/index.page
/usr/share/help/pl/eog/introduction.page
/usr/share/help/pl/eog/legal.xml
/usr/share/help/pl/eog/license.page
/usr/share/help/pl/eog/open.page
/usr/share/help/pl/eog/plugin-exif-digital.page
/usr/share/help/pl/eog/plugin-fullscreen-background.page
/usr/share/help/pl/eog/plugin-fullscreen-double-click.page
/usr/share/help/pl/eog/plugin-python-console.page
/usr/share/help/pl/eog/plugin-send-by-mail.page
/usr/share/help/pl/eog/plugin-slideshow-shuffle.page
/usr/share/help/pl/eog/plugin-zoom-width.page
/usr/share/help/pl/eog/plugins.page
/usr/share/help/pl/eog/preferences.page
/usr/share/help/pl/eog/print.page
/usr/share/help/pl/eog/rename-multiple.page
/usr/share/help/pl/eog/slideshow.page
/usr/share/help/pl/eog/translate.page
/usr/share/help/pl/eog/view.page
/usr/share/help/pl/eog/zoom.page
/usr/share/help/pt/eog/bug-filing.page
/usr/share/help/pt/eog/commandline.page
/usr/share/help/pt/eog/copy-paste.page
/usr/share/help/pt/eog/default.page
/usr/share/help/pt/eog/desktop-background.page
/usr/share/help/pt/eog/develop.page
/usr/share/help/pt/eog/documentation.page
/usr/share/help/pt/eog/edit.page
/usr/share/help/pt/eog/figures/multiple-convert.png
/usr/share/help/pt/eog/figures/multiple-rename-count.png
/usr/share/help/pt/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/pt/eog/figures/org.gnome.eog.svg
/usr/share/help/pt/eog/figures/plugins-all.png
/usr/share/help/pt/eog/figures/prefs-plugins.png
/usr/share/help/pt/eog/flip-rotate.page
/usr/share/help/pt/eog/format-change.page
/usr/share/help/pt/eog/formats-save.page
/usr/share/help/pt/eog/formats-view.page
/usr/share/help/pt/eog/index.page
/usr/share/help/pt/eog/introduction.page
/usr/share/help/pt/eog/legal.xml
/usr/share/help/pt/eog/license.page
/usr/share/help/pt/eog/open.page
/usr/share/help/pt/eog/plugin-exif-digital.page
/usr/share/help/pt/eog/plugin-fullscreen-background.page
/usr/share/help/pt/eog/plugin-fullscreen-double-click.page
/usr/share/help/pt/eog/plugin-python-console.page
/usr/share/help/pt/eog/plugin-send-by-mail.page
/usr/share/help/pt/eog/plugin-slideshow-shuffle.page
/usr/share/help/pt/eog/plugin-zoom-width.page
/usr/share/help/pt/eog/plugins.page
/usr/share/help/pt/eog/preferences.page
/usr/share/help/pt/eog/print.page
/usr/share/help/pt/eog/rename-multiple.page
/usr/share/help/pt/eog/slideshow.page
/usr/share/help/pt/eog/translate.page
/usr/share/help/pt/eog/view.page
/usr/share/help/pt/eog/zoom.page
/usr/share/help/pt_BR/eog/bug-filing.page
/usr/share/help/pt_BR/eog/commandline.page
/usr/share/help/pt_BR/eog/copy-paste.page
/usr/share/help/pt_BR/eog/default.page
/usr/share/help/pt_BR/eog/desktop-background.page
/usr/share/help/pt_BR/eog/develop.page
/usr/share/help/pt_BR/eog/documentation.page
/usr/share/help/pt_BR/eog/edit.page
/usr/share/help/pt_BR/eog/figures/multiple-convert.png
/usr/share/help/pt_BR/eog/figures/multiple-rename-count.png
/usr/share/help/pt_BR/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/pt_BR/eog/figures/org.gnome.eog.svg
/usr/share/help/pt_BR/eog/figures/plugins-all.png
/usr/share/help/pt_BR/eog/figures/prefs-plugins.png
/usr/share/help/pt_BR/eog/flip-rotate.page
/usr/share/help/pt_BR/eog/format-change.page
/usr/share/help/pt_BR/eog/formats-save.page
/usr/share/help/pt_BR/eog/formats-view.page
/usr/share/help/pt_BR/eog/index.page
/usr/share/help/pt_BR/eog/introduction.page
/usr/share/help/pt_BR/eog/legal.xml
/usr/share/help/pt_BR/eog/license.page
/usr/share/help/pt_BR/eog/open.page
/usr/share/help/pt_BR/eog/plugin-exif-digital.page
/usr/share/help/pt_BR/eog/plugin-fullscreen-background.page
/usr/share/help/pt_BR/eog/plugin-fullscreen-double-click.page
/usr/share/help/pt_BR/eog/plugin-python-console.page
/usr/share/help/pt_BR/eog/plugin-send-by-mail.page
/usr/share/help/pt_BR/eog/plugin-slideshow-shuffle.page
/usr/share/help/pt_BR/eog/plugin-zoom-width.page
/usr/share/help/pt_BR/eog/plugins.page
/usr/share/help/pt_BR/eog/preferences.page
/usr/share/help/pt_BR/eog/print.page
/usr/share/help/pt_BR/eog/rename-multiple.page
/usr/share/help/pt_BR/eog/slideshow.page
/usr/share/help/pt_BR/eog/translate.page
/usr/share/help/pt_BR/eog/view.page
/usr/share/help/pt_BR/eog/zoom.page
/usr/share/help/ro/eog/bug-filing.page
/usr/share/help/ro/eog/commandline.page
/usr/share/help/ro/eog/copy-paste.page
/usr/share/help/ro/eog/default.page
/usr/share/help/ro/eog/desktop-background.page
/usr/share/help/ro/eog/develop.page
/usr/share/help/ro/eog/documentation.page
/usr/share/help/ro/eog/edit.page
/usr/share/help/ro/eog/figures/multiple-convert.png
/usr/share/help/ro/eog/figures/multiple-rename-count.png
/usr/share/help/ro/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/ro/eog/figures/org.gnome.eog.svg
/usr/share/help/ro/eog/figures/plugins-all.png
/usr/share/help/ro/eog/figures/prefs-plugins.png
/usr/share/help/ro/eog/flip-rotate.page
/usr/share/help/ro/eog/format-change.page
/usr/share/help/ro/eog/formats-save.page
/usr/share/help/ro/eog/formats-view.page
/usr/share/help/ro/eog/index.page
/usr/share/help/ro/eog/introduction.page
/usr/share/help/ro/eog/legal.xml
/usr/share/help/ro/eog/license.page
/usr/share/help/ro/eog/open.page
/usr/share/help/ro/eog/plugin-exif-digital.page
/usr/share/help/ro/eog/plugin-fullscreen-background.page
/usr/share/help/ro/eog/plugin-fullscreen-double-click.page
/usr/share/help/ro/eog/plugin-python-console.page
/usr/share/help/ro/eog/plugin-send-by-mail.page
/usr/share/help/ro/eog/plugin-slideshow-shuffle.page
/usr/share/help/ro/eog/plugin-zoom-width.page
/usr/share/help/ro/eog/plugins.page
/usr/share/help/ro/eog/preferences.page
/usr/share/help/ro/eog/print.page
/usr/share/help/ro/eog/rename-multiple.page
/usr/share/help/ro/eog/slideshow.page
/usr/share/help/ro/eog/translate.page
/usr/share/help/ro/eog/view.page
/usr/share/help/ro/eog/zoom.page
/usr/share/help/ru/eog/bug-filing.page
/usr/share/help/ru/eog/commandline.page
/usr/share/help/ru/eog/copy-paste.page
/usr/share/help/ru/eog/default.page
/usr/share/help/ru/eog/desktop-background.page
/usr/share/help/ru/eog/develop.page
/usr/share/help/ru/eog/documentation.page
/usr/share/help/ru/eog/edit.page
/usr/share/help/ru/eog/figures/multiple-convert.png
/usr/share/help/ru/eog/figures/multiple-rename-count.png
/usr/share/help/ru/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/ru/eog/figures/org.gnome.eog.svg
/usr/share/help/ru/eog/figures/plugins-all.png
/usr/share/help/ru/eog/figures/prefs-plugins.png
/usr/share/help/ru/eog/flip-rotate.page
/usr/share/help/ru/eog/format-change.page
/usr/share/help/ru/eog/formats-save.page
/usr/share/help/ru/eog/formats-view.page
/usr/share/help/ru/eog/index.page
/usr/share/help/ru/eog/introduction.page
/usr/share/help/ru/eog/legal.xml
/usr/share/help/ru/eog/license.page
/usr/share/help/ru/eog/open.page
/usr/share/help/ru/eog/plugin-exif-digital.page
/usr/share/help/ru/eog/plugin-fullscreen-background.page
/usr/share/help/ru/eog/plugin-fullscreen-double-click.page
/usr/share/help/ru/eog/plugin-python-console.page
/usr/share/help/ru/eog/plugin-send-by-mail.page
/usr/share/help/ru/eog/plugin-slideshow-shuffle.page
/usr/share/help/ru/eog/plugin-zoom-width.page
/usr/share/help/ru/eog/plugins.page
/usr/share/help/ru/eog/preferences.page
/usr/share/help/ru/eog/print.page
/usr/share/help/ru/eog/rename-multiple.page
/usr/share/help/ru/eog/slideshow.page
/usr/share/help/ru/eog/translate.page
/usr/share/help/ru/eog/view.page
/usr/share/help/ru/eog/zoom.page
/usr/share/help/sl/eog/bug-filing.page
/usr/share/help/sl/eog/commandline.page
/usr/share/help/sl/eog/copy-paste.page
/usr/share/help/sl/eog/default.page
/usr/share/help/sl/eog/desktop-background.page
/usr/share/help/sl/eog/develop.page
/usr/share/help/sl/eog/documentation.page
/usr/share/help/sl/eog/edit.page
/usr/share/help/sl/eog/figures/multiple-convert.png
/usr/share/help/sl/eog/figures/multiple-rename-count.png
/usr/share/help/sl/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/sl/eog/figures/org.gnome.eog.svg
/usr/share/help/sl/eog/figures/plugins-all.png
/usr/share/help/sl/eog/figures/prefs-plugins.png
/usr/share/help/sl/eog/flip-rotate.page
/usr/share/help/sl/eog/format-change.page
/usr/share/help/sl/eog/formats-save.page
/usr/share/help/sl/eog/formats-view.page
/usr/share/help/sl/eog/index.page
/usr/share/help/sl/eog/introduction.page
/usr/share/help/sl/eog/legal.xml
/usr/share/help/sl/eog/license.page
/usr/share/help/sl/eog/open.page
/usr/share/help/sl/eog/plugin-exif-digital.page
/usr/share/help/sl/eog/plugin-fullscreen-background.page
/usr/share/help/sl/eog/plugin-fullscreen-double-click.page
/usr/share/help/sl/eog/plugin-python-console.page
/usr/share/help/sl/eog/plugin-send-by-mail.page
/usr/share/help/sl/eog/plugin-slideshow-shuffle.page
/usr/share/help/sl/eog/plugin-zoom-width.page
/usr/share/help/sl/eog/plugins.page
/usr/share/help/sl/eog/preferences.page
/usr/share/help/sl/eog/print.page
/usr/share/help/sl/eog/rename-multiple.page
/usr/share/help/sl/eog/slideshow.page
/usr/share/help/sl/eog/translate.page
/usr/share/help/sl/eog/view.page
/usr/share/help/sl/eog/zoom.page
/usr/share/help/sv/eog/bug-filing.page
/usr/share/help/sv/eog/commandline.page
/usr/share/help/sv/eog/copy-paste.page
/usr/share/help/sv/eog/default.page
/usr/share/help/sv/eog/desktop-background.page
/usr/share/help/sv/eog/develop.page
/usr/share/help/sv/eog/documentation.page
/usr/share/help/sv/eog/edit.page
/usr/share/help/sv/eog/figures/multiple-convert.png
/usr/share/help/sv/eog/figures/multiple-rename-count.png
/usr/share/help/sv/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/sv/eog/figures/org.gnome.eog.svg
/usr/share/help/sv/eog/figures/plugins-all.png
/usr/share/help/sv/eog/figures/prefs-plugins.png
/usr/share/help/sv/eog/flip-rotate.page
/usr/share/help/sv/eog/format-change.page
/usr/share/help/sv/eog/formats-save.page
/usr/share/help/sv/eog/formats-view.page
/usr/share/help/sv/eog/index.page
/usr/share/help/sv/eog/introduction.page
/usr/share/help/sv/eog/legal.xml
/usr/share/help/sv/eog/license.page
/usr/share/help/sv/eog/open.page
/usr/share/help/sv/eog/plugin-exif-digital.page
/usr/share/help/sv/eog/plugin-fullscreen-background.page
/usr/share/help/sv/eog/plugin-fullscreen-double-click.page
/usr/share/help/sv/eog/plugin-python-console.page
/usr/share/help/sv/eog/plugin-send-by-mail.page
/usr/share/help/sv/eog/plugin-slideshow-shuffle.page
/usr/share/help/sv/eog/plugin-zoom-width.page
/usr/share/help/sv/eog/plugins.page
/usr/share/help/sv/eog/preferences.page
/usr/share/help/sv/eog/print.page
/usr/share/help/sv/eog/rename-multiple.page
/usr/share/help/sv/eog/slideshow.page
/usr/share/help/sv/eog/translate.page
/usr/share/help/sv/eog/view.page
/usr/share/help/sv/eog/zoom.page
/usr/share/help/te/eog/bug-filing.page
/usr/share/help/te/eog/commandline.page
/usr/share/help/te/eog/copy-paste.page
/usr/share/help/te/eog/default.page
/usr/share/help/te/eog/desktop-background.page
/usr/share/help/te/eog/develop.page
/usr/share/help/te/eog/documentation.page
/usr/share/help/te/eog/edit.page
/usr/share/help/te/eog/figures/multiple-convert.png
/usr/share/help/te/eog/figures/multiple-rename-count.png
/usr/share/help/te/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/te/eog/figures/org.gnome.eog.svg
/usr/share/help/te/eog/figures/plugins-all.png
/usr/share/help/te/eog/figures/prefs-plugins.png
/usr/share/help/te/eog/flip-rotate.page
/usr/share/help/te/eog/format-change.page
/usr/share/help/te/eog/formats-save.page
/usr/share/help/te/eog/formats-view.page
/usr/share/help/te/eog/index.page
/usr/share/help/te/eog/introduction.page
/usr/share/help/te/eog/legal.xml
/usr/share/help/te/eog/license.page
/usr/share/help/te/eog/open.page
/usr/share/help/te/eog/plugin-exif-digital.page
/usr/share/help/te/eog/plugin-fullscreen-background.page
/usr/share/help/te/eog/plugin-fullscreen-double-click.page
/usr/share/help/te/eog/plugin-python-console.page
/usr/share/help/te/eog/plugin-send-by-mail.page
/usr/share/help/te/eog/plugin-slideshow-shuffle.page
/usr/share/help/te/eog/plugin-zoom-width.page
/usr/share/help/te/eog/plugins.page
/usr/share/help/te/eog/preferences.page
/usr/share/help/te/eog/print.page
/usr/share/help/te/eog/rename-multiple.page
/usr/share/help/te/eog/slideshow.page
/usr/share/help/te/eog/translate.page
/usr/share/help/te/eog/view.page
/usr/share/help/te/eog/zoom.page
/usr/share/help/th/eog/bug-filing.page
/usr/share/help/th/eog/commandline.page
/usr/share/help/th/eog/copy-paste.page
/usr/share/help/th/eog/default.page
/usr/share/help/th/eog/desktop-background.page
/usr/share/help/th/eog/develop.page
/usr/share/help/th/eog/documentation.page
/usr/share/help/th/eog/edit.page
/usr/share/help/th/eog/figures/multiple-convert.png
/usr/share/help/th/eog/figures/multiple-rename-count.png
/usr/share/help/th/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/th/eog/figures/org.gnome.eog.svg
/usr/share/help/th/eog/figures/plugins-all.png
/usr/share/help/th/eog/figures/prefs-plugins.png
/usr/share/help/th/eog/flip-rotate.page
/usr/share/help/th/eog/format-change.page
/usr/share/help/th/eog/formats-save.page
/usr/share/help/th/eog/formats-view.page
/usr/share/help/th/eog/index.page
/usr/share/help/th/eog/introduction.page
/usr/share/help/th/eog/legal.xml
/usr/share/help/th/eog/license.page
/usr/share/help/th/eog/open.page
/usr/share/help/th/eog/plugin-exif-digital.page
/usr/share/help/th/eog/plugin-fullscreen-background.page
/usr/share/help/th/eog/plugin-fullscreen-double-click.page
/usr/share/help/th/eog/plugin-python-console.page
/usr/share/help/th/eog/plugin-send-by-mail.page
/usr/share/help/th/eog/plugin-slideshow-shuffle.page
/usr/share/help/th/eog/plugin-zoom-width.page
/usr/share/help/th/eog/plugins.page
/usr/share/help/th/eog/preferences.page
/usr/share/help/th/eog/print.page
/usr/share/help/th/eog/rename-multiple.page
/usr/share/help/th/eog/slideshow.page
/usr/share/help/th/eog/translate.page
/usr/share/help/th/eog/view.page
/usr/share/help/th/eog/zoom.page
/usr/share/help/tr/eog/bug-filing.page
/usr/share/help/tr/eog/commandline.page
/usr/share/help/tr/eog/copy-paste.page
/usr/share/help/tr/eog/default.page
/usr/share/help/tr/eog/desktop-background.page
/usr/share/help/tr/eog/develop.page
/usr/share/help/tr/eog/documentation.page
/usr/share/help/tr/eog/edit.page
/usr/share/help/tr/eog/figures/multiple-convert.png
/usr/share/help/tr/eog/figures/multiple-rename-count.png
/usr/share/help/tr/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/tr/eog/figures/org.gnome.eog.svg
/usr/share/help/tr/eog/figures/plugins-all.png
/usr/share/help/tr/eog/figures/prefs-plugins.png
/usr/share/help/tr/eog/flip-rotate.page
/usr/share/help/tr/eog/format-change.page
/usr/share/help/tr/eog/formats-save.page
/usr/share/help/tr/eog/formats-view.page
/usr/share/help/tr/eog/index.page
/usr/share/help/tr/eog/introduction.page
/usr/share/help/tr/eog/legal.xml
/usr/share/help/tr/eog/license.page
/usr/share/help/tr/eog/open.page
/usr/share/help/tr/eog/plugin-exif-digital.page
/usr/share/help/tr/eog/plugin-fullscreen-background.page
/usr/share/help/tr/eog/plugin-fullscreen-double-click.page
/usr/share/help/tr/eog/plugin-python-console.page
/usr/share/help/tr/eog/plugin-send-by-mail.page
/usr/share/help/tr/eog/plugin-slideshow-shuffle.page
/usr/share/help/tr/eog/plugin-zoom-width.page
/usr/share/help/tr/eog/plugins.page
/usr/share/help/tr/eog/preferences.page
/usr/share/help/tr/eog/print.page
/usr/share/help/tr/eog/rename-multiple.page
/usr/share/help/tr/eog/slideshow.page
/usr/share/help/tr/eog/translate.page
/usr/share/help/tr/eog/view.page
/usr/share/help/tr/eog/zoom.page
/usr/share/help/uk/eog/bug-filing.page
/usr/share/help/uk/eog/commandline.page
/usr/share/help/uk/eog/copy-paste.page
/usr/share/help/uk/eog/default.page
/usr/share/help/uk/eog/desktop-background.page
/usr/share/help/uk/eog/develop.page
/usr/share/help/uk/eog/documentation.page
/usr/share/help/uk/eog/edit.page
/usr/share/help/uk/eog/figures/multiple-convert.png
/usr/share/help/uk/eog/figures/multiple-rename-count.png
/usr/share/help/uk/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/uk/eog/figures/org.gnome.eog.svg
/usr/share/help/uk/eog/figures/plugins-all.png
/usr/share/help/uk/eog/figures/prefs-plugins.png
/usr/share/help/uk/eog/flip-rotate.page
/usr/share/help/uk/eog/format-change.page
/usr/share/help/uk/eog/formats-save.page
/usr/share/help/uk/eog/formats-view.page
/usr/share/help/uk/eog/index.page
/usr/share/help/uk/eog/introduction.page
/usr/share/help/uk/eog/legal.xml
/usr/share/help/uk/eog/license.page
/usr/share/help/uk/eog/open.page
/usr/share/help/uk/eog/plugin-exif-digital.page
/usr/share/help/uk/eog/plugin-fullscreen-background.page
/usr/share/help/uk/eog/plugin-fullscreen-double-click.page
/usr/share/help/uk/eog/plugin-python-console.page
/usr/share/help/uk/eog/plugin-send-by-mail.page
/usr/share/help/uk/eog/plugin-slideshow-shuffle.page
/usr/share/help/uk/eog/plugin-zoom-width.page
/usr/share/help/uk/eog/plugins.page
/usr/share/help/uk/eog/preferences.page
/usr/share/help/uk/eog/print.page
/usr/share/help/uk/eog/rename-multiple.page
/usr/share/help/uk/eog/slideshow.page
/usr/share/help/uk/eog/translate.page
/usr/share/help/uk/eog/view.page
/usr/share/help/uk/eog/zoom.page
/usr/share/help/zh_CN/eog/bug-filing.page
/usr/share/help/zh_CN/eog/commandline.page
/usr/share/help/zh_CN/eog/copy-paste.page
/usr/share/help/zh_CN/eog/default.page
/usr/share/help/zh_CN/eog/desktop-background.page
/usr/share/help/zh_CN/eog/develop.page
/usr/share/help/zh_CN/eog/documentation.page
/usr/share/help/zh_CN/eog/edit.page
/usr/share/help/zh_CN/eog/figures/multiple-convert.png
/usr/share/help/zh_CN/eog/figures/multiple-rename-count.png
/usr/share/help/zh_CN/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/zh_CN/eog/figures/org.gnome.eog.svg
/usr/share/help/zh_CN/eog/figures/plugins-all.png
/usr/share/help/zh_CN/eog/figures/prefs-plugins.png
/usr/share/help/zh_CN/eog/flip-rotate.page
/usr/share/help/zh_CN/eog/format-change.page
/usr/share/help/zh_CN/eog/formats-save.page
/usr/share/help/zh_CN/eog/formats-view.page
/usr/share/help/zh_CN/eog/index.page
/usr/share/help/zh_CN/eog/introduction.page
/usr/share/help/zh_CN/eog/legal.xml
/usr/share/help/zh_CN/eog/license.page
/usr/share/help/zh_CN/eog/open.page
/usr/share/help/zh_CN/eog/plugin-exif-digital.page
/usr/share/help/zh_CN/eog/plugin-fullscreen-background.page
/usr/share/help/zh_CN/eog/plugin-fullscreen-double-click.page
/usr/share/help/zh_CN/eog/plugin-python-console.page
/usr/share/help/zh_CN/eog/plugin-send-by-mail.page
/usr/share/help/zh_CN/eog/plugin-slideshow-shuffle.page
/usr/share/help/zh_CN/eog/plugin-zoom-width.page
/usr/share/help/zh_CN/eog/plugins.page
/usr/share/help/zh_CN/eog/preferences.page
/usr/share/help/zh_CN/eog/print.page
/usr/share/help/zh_CN/eog/rename-multiple.page
/usr/share/help/zh_CN/eog/slideshow.page
/usr/share/help/zh_CN/eog/translate.page
/usr/share/help/zh_CN/eog/view.page
/usr/share/help/zh_CN/eog/zoom.page
/usr/share/help/zh_TW/eog/bug-filing.page
/usr/share/help/zh_TW/eog/commandline.page
/usr/share/help/zh_TW/eog/copy-paste.page
/usr/share/help/zh_TW/eog/default.page
/usr/share/help/zh_TW/eog/desktop-background.page
/usr/share/help/zh_TW/eog/develop.page
/usr/share/help/zh_TW/eog/documentation.page
/usr/share/help/zh_TW/eog/edit.page
/usr/share/help/zh_TW/eog/figures/multiple-convert.png
/usr/share/help/zh_TW/eog/figures/multiple-rename-count.png
/usr/share/help/zh_TW/eog/figures/org.gnome.eog-symbolic.svg
/usr/share/help/zh_TW/eog/figures/org.gnome.eog.svg
/usr/share/help/zh_TW/eog/figures/plugins-all.png
/usr/share/help/zh_TW/eog/figures/prefs-plugins.png
/usr/share/help/zh_TW/eog/flip-rotate.page
/usr/share/help/zh_TW/eog/format-change.page
/usr/share/help/zh_TW/eog/formats-save.page
/usr/share/help/zh_TW/eog/formats-view.page
/usr/share/help/zh_TW/eog/index.page
/usr/share/help/zh_TW/eog/introduction.page
/usr/share/help/zh_TW/eog/legal.xml
/usr/share/help/zh_TW/eog/license.page
/usr/share/help/zh_TW/eog/open.page
/usr/share/help/zh_TW/eog/plugin-exif-digital.page
/usr/share/help/zh_TW/eog/plugin-fullscreen-background.page
/usr/share/help/zh_TW/eog/plugin-fullscreen-double-click.page
/usr/share/help/zh_TW/eog/plugin-python-console.page
/usr/share/help/zh_TW/eog/plugin-send-by-mail.page
/usr/share/help/zh_TW/eog/plugin-slideshow-shuffle.page
/usr/share/help/zh_TW/eog/plugin-zoom-width.page
/usr/share/help/zh_TW/eog/plugins.page
/usr/share/help/zh_TW/eog/preferences.page
/usr/share/help/zh_TW/eog/print.page
/usr/share/help/zh_TW/eog/rename-multiple.page
/usr/share/help/zh_TW/eog/slideshow.page
/usr/share/help/zh_TW/eog/translate.page
/usr/share/help/zh_TW/eog/view.page
/usr/share/help/zh_TW/eog/zoom.page

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-eog

%files lib
%defattr(-,root,root,-)
/usr/lib64/eog/libeog.so
/usr/lib64/eog/plugins/libfullscreen.so
/usr/lib64/eog/plugins/libreload.so
/usr/lib64/eog/plugins/libstatusbar-date.so
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/eog/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/eog/99449fd3e6417f1f32dbe2a5b252880badb25704

%files locales -f eog.lang
%defattr(-,root,root,-)

